export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export PATH=".:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export GO111MODULE=on
export GOROOT="$HOME/bin/go"
export TERM=xterm-256color
export EDITOR="nvim"
export PAGER=less
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
export MOZ_USE_XINPUT2=1
